---
title: "The Effect of Children on Women's Labor Supply: A Bayesian Replication Analysis"
author: "Jennah Gosciak"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document
---

```{r setup, set.seed(1690)}
#knitr::opts_chunk$set(cache = T)
```

```{r, include = F}
#options(warn=-1)
suppressPackageStartupMessages(library(tibble))
library(tidyverse)
library(knitr)
library(rgl)
library(rstan)
options(mc.cores = parallel::detectCores())
library(readr)
library(dplyr)
library(ggplot2)
library(tidyquant)
library(purrr)
library(rstanarm)
library(loo)
library(bayesplot)
library(haven)

set.seed(1690)
```


```{r}
## load data
df <- read_dta("../00_data/sample1.dta")
df_samp <- df %>% 
  sample_n(3000)

df_samp <- df_samp %>% 
  mutate(across(c("age", "age_fbirth"), ~ . - mean(., na.rm = T))) %>% 
  mutate(l_incwage = if_else(incwage <= 0, log(1), log(incwage)),
         l_wkswork1 = if_else(wkswork1 <= 0, log(1), log(wkswork1)))

df_samp %>% 
  group_by(samesex) %>% 
  summarize(n = n())
```

```{r}
hist(df_samp$incwage)

hist(df_samp$l_incwage)
```



## Linear model with log-transformed outcome
```{r}
m <- rep(0, 8)
s<- rep(1, 8)

stan_data <- list(N = nrow(df_samp), K = 6, y = df_samp$l_incwage, 
                                        X = df_samp[, c("cnum_mt2", "age", "age_fbirth",
                                                        "r_black", "hisp", "r_oth")],
                                        prior_only = TRUE, m = m, 
                                        scale = s)
pre_l <- stan("linear2.stan", data = stan_data, seed = 12345)
# print output
print(pre_l, pars = c("alpha", "beta", "sigma"))
```

```{r}
hist(as.numeric(rstan::extract(pre_l, par = "yrep")$yrep))
```

```{r}
pairs(pre_l, pars = c("alpha", "beta", "sigma"))
```

```{r}
loo_pre <- loo(pre_l)
loo_pre
```

```{r}
pp_check(as.numeric(stan_data$y),
  rstan::extract(pre_l, par = "yrep")$yrep[1:150, ],
  ppc_dens_overlay
)
```

```{r}
stan_data$prior_only = FALSE
post_l <- stan("linear2.stan", data = stan_data,
                                        seed = 12345)
# print output
print(post_l, pars = c("alpha", "beta", "sigma"))
```

```{r}
hist(as.numeric(rstan::extract(post_l, par = "yrep")$yrep))
```

```{r}
pairs(post_l, pars = c("alpha", "beta", "sigma"))
```

```{r}
# loo_post <- loo(post_l)
# loo_post
# 
# loo_compare(loo_pre, loo_post)
```

```{r}
pp_check(as.numeric(stan_data$y),
  rstan::extract(post_l, par = "yrep")$yrep[1:150, ],
  ppc_dens_overlay
)
```

## Model with rstanarm and Gamma distribution

```{r}
stan_data <- list(N = nrow(df_samp), K = 6, 
                                        y = df_samp$incwage, 
                                        X = df_samp[, c("cnum_mt2", "age", "age_fbirth",
                                                        "r_black", "hisp", "r_oth")],
                                        prior_only = FALSE, m = m, 
                                        scale = s, r = 0.5)
post_gamma <- stan("linear_gamma.stan", data = stan_data,
                                         seed = 12345, chains = 1)
# print output
print(post_gamma, pars = c("alpha", "beta", "shape"))
```


```{r}
hist_val <- df_samp %>% 
  filter(incwage > 0) %>% 
  pull(l_incwage)

hist(hist_val)

hist_val2 <- df_samp %>% 
  pull(l_incwage)

hist(hist_val2)
```

## IV with Heckman Two-Step Process

```{r}
df_samp2 <- df_samp %>% 
  sample_n(1000)

df_movers <- df_samp2 %>% 
  filter(cnum_mt2 == 1)

df_stayers <- df_samp2 %>% 
  filter(cnum_mt2 == 0)

a <- c(0, 5, rep(0, 7))
stan_data_iv <- list(N = nrow(df_samp2),
                  N_child = nrow(df_movers),
                  N_nochild = nrow(df_stayers),
                  K = 6,
                  X_child_s = df_movers[, c("samesex", "cnum_mt2", "age", "age_fbirth",
                                            "r_black", "hisp", "r_oth")],
                  X_nochild_s = df_stayers[, c("samesex", "cnum_mt2", "age", "age_fbirth", 
                                               "r_black", "hisp", "r_oth")],
                  X_child = df_movers[, c("cnum_mt2", "age", "age_fbirth",
                                          "r_black", "hisp", "r_oth")],
                  X_nochild = df_stayers[, c("cnum_mt2", "age", "age_fbirth", 
                                             "r_black", "hisp", "r_oth")],
                  y_child = df_movers$l_incwage,
                  y_nochild = df_stayers$l_incwage,
                  prior_only = TRUE,
                  m = rep(-0.1, 5), #c(-1, a, 3, 0.5, -1),
                  scale = rep(0.2, 5), r = 100)
```


```{r}
pre_iv <- stan("iv_bin2.stan", data = stan_data_iv, seed = 1234, init = 1, chains = 1, control = list(adapt_delta = 0.99))
print(pre_iv, pars = c("alpha0", "alpha1", "beta0", "beta1", "beta2", "sigma"))
```

```{r}
pp_check(c(as.numeric(stan_data_iv$y_movers), as.numeric(stan_data_iv$y_stayers)),
  rstan::extract(pre_iv, par = "yrep")$yrep[1:150, ],
  ppc_dens_overlay
)
```


```{r}
stan_data_iv$prior_only <- FALSE
post_iv <- stan("iv_bin2.stan", data = stan_data_iv, seed = 1234, control = list(adapt_delta = 0.99))
print(post_iv, pars = c("alpha0", "alpha1", "beta0", "beta1", "beta2", "sigma", "rho"))
```
```{r}
pairs(post_iv, pars = c("alpha1"))
```
```{r}
pairs(post_iv, pars = c("beta1"))
```

```{r}
# loo_post_iv <- loo(post_iv)
# loo_post_iv
```

```{r}
pp_check(c(as.numeric(stan_data_iv$y_movers), as.numeric(stan_data_iv$y_stayers)),
  rstan::extract(post_iv, par = "yrep")$yrep[1:150, ],
  ppc_dens_overlay
)
```

```{r}
#loo_compare(loo_pre_iv, loo_post_iv)
```





