---
title: "Final Project"
author: "Jennah Gosciak"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document
---

```{r setup, set.seed(1690)}
#knitr::opts_chunk$set(cache = T)
```

```{r, include = F}
#options(warn=-1)
suppressPackageStartupMessages(library(tibble))
library(tidyverse)
library(knitr)
library(rgl)
library(rstan)
options(mc.cores = parallel::detectCores())
library(readr)
library(dplyr)
library(ggplot2)
library(tidyquant)
library(purrr)
library(rstanarm)
library(loo)
library(bayesplot)
library(haven)
```

```{r}
## load data
df <- read_dta("../00_data/ICPSR_34563-V2/ICPSR_34563/DS0001/34563-0001-Zipped_package/mto_sci_puf_pseudo_20130206.dta")
df

df_cell <- read_dta("../00_data/ICPSR_34563-V2/ICPSR_34563/DS0001/34563-0001-Zipped_package/mto_sci_puf_cells_20130206.dta")
df_cell
```
```{r}
df_cell %>% 
  select(c("ra_group")) %>%
  group_by(ra_group) %>% 
  summarize(n = n())
```


```{r}
lq <- c(-0.1, -0.1)
m <- c(0, 0, 0)
uq <- c(0.1, 0.1, 0.1)
  
a_s_beta  <- GLD_solver_LBFGS(lower_quartile = lq[1],  median = m[1], upper_quartile = uq[1],
                        other_quantile = oq[1], alpha = 0.95)
a_s_alpha <- GLD_solver_LBFGS(lower_quartile = lq[2],  median = m[2], upper_quartile = uq[3],
                        other_quantile = oq[2], alpha = 0.95)
a_s_sigma <- GLD_solver_LBFGS(lower_quartile = lq[3]-0.01,  median = m[3], upper_quartile = uq[3],
                        other_quantile = 0, alpha = 0)

# asymmetry and steepness for prior distrib
a <- c(beta = a_s_beta[1], alpha = a_s_alpha[1], sigma = a_s_sigma[1])
s <- c(beta = a_s_beta[2], alpha = a_s_alpha[2], sigma = a_s_sigma[2])
```

```{r}
post <- stan("linear_capm.stan", data = list(N = length(R_i), K = 1, 
                                             y = (R_i - R_f), 
                                        X = as.matrix(R_m - R_f),
                                        prior_only = FALSE, m = m, 
                                        r = r, a = a, s = s),
                                        seed = 12345)
post
```


