---
title: "Supplemental Analyses"
author: "Jennah Gosciak"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document
---

```{r setup, set.seed(1690)}
```

```{r, include = F}
#options(warn=-1)
suppressPackageStartupMessages(library(tibble))
library(tidyverse)
library(knitr)
library(rgl)
library(rstan)
options(mc.cores = parallel::detectCores())
library(readr)
library(dplyr)
library(ggplot2)
library(purrr)
library(rstanarm)
library(loo)
library(bayesplot)
library(haven)

set.seed(1690)
```


```{r}
## load data
df <- read_dta("../00_data/sample1.dta")
df_samp <- df %>% 
  sample_n(1000)

df_samp <- df_samp %>% 
  mutate(across(c("age", "age_fbirth"), ~ . - mean(., na.rm = T))) %>% 
  mutate(l_incwage = if_else(incwage <= 0, log(1), log(incwage)),
         l_wkswork1 = if_else(wkswork1 <= 0, log(1), log(wkswork1)),
         incwage_mod = if_else(incwage <= 0, 1, incwage))

df_samp %>% 
  group_by(samesex) %>% 
  summarize(n = n())
```

## Run outcome with Gamma distribution

* Uses log link
* Similar to implementation in `rstanarm`

```{r}
writeLines(readLines("linear_gamma.stan"))
```


```{r, cache = TRUE}
m <- rep(-0.1, 10)
s<- rep(1, 10)

stan_data <- list(N = nrow(df_samp), K = 8, 
                                        y = df_samp$incwage, 
                                        X = df_samp[, c("cnum_mt2", "age", "age_fbirth", "f_boy", 
                                                   "s_boy", "r_black", "hisp", "r_oth")],
                                        prior_only = FALSE, m = m, 
                                        scale = s, r = 0.5)
post_gamma <- stan("linear_gamma.stan", data = stan_data,
                                         seed = 12345)
# print output
print(post_gamma, pars = c("alpha", "beta", "shape"))
```
```{r}
pp_check(as.numeric(stan_data$y),
  rstan::extract(post_gamma, par = "yrep")$yrep[sample(1:length(stan_data$y), size = 150), ],
  ppc_dens_overlay
)
```

```{r}
loo(post_gamma)
```










